project_id = "fttkdloraaraeqvijwtv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[services]
[services.openai]
url = "https://api.openai.com"