// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttkdloraaraeqvijwtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGtkbG9yYWFyYWVxdmlqd3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODczOTUsImV4cCI6MjA1MTg2MzM5NX0.PhlpHPTcl7XFu9H2A9-pUASI3U0uOA_UCilXIhfCG4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);